name: Create GitHub Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
  
jobs:
  create-release:
    name: Create Release on main push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git fetch --tags

      - name: Determine next tag
        id: next_tag
        run: |
          # セマンティックバージョンのベースを定義（必要なら変更可能）
          BASE_VERSION="1.0.0"

          # 既存のタグを抽出し、末尾が +数字 であるものに限定して最大値を探す
          LAST_NUMBER=$(git tag | grep "^${BASE_VERSION}+[0-9]\+$" | sed -E "s/^${BASE_VERSION}\+//" | sort -n | tail -n1)

          if [ -z "$LAST_NUMBER" ]; then
            NEXT_NUMBER=1
          else
            NEXT_NUMBER=$((LAST_NUMBER + 1))
          fi

          NEXT_TAG="${BASE_VERSION}+${NEXT_NUMBER}"
          echo "Next tag will be $NEXT_TAG"
          echo "tag=$NEXT_TAG" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag ${{ steps.next_tag.outputs.tag }}
          git push origin ${{ steps.next_tag.outputs.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.next_tag.outputs.tag }}
          name: Release ${{ steps.next_tag.outputs.tag }}
          generate_release_notes: true
